### ISSUE TITLE
Smaller stepsize for 0K finale

### ISSUE THREAD

**Issue by jillfrost** [steventopper/TransRot#2]
Hi Steven,

I have been using the 0K finale to ensure that I'm finding the lowest possible energy structure. It would be helpful if the stepsize could be set to 1/100 of the original stepsize during this part.

Jillian

**Comment by steventopper** [comment]
Hi Jillian, thanks for the submission.

By default, both translation and rotation stepsize will now be set to 1/100 of their value set in the config during a 0K finale. This seems like a straight enhancement of the feature, so I haven't included a method to disable this. However, if you run into situations where you would need finer control over or to disable the finale stepsize, please let me know and I'll add a new configuration option.

In going through the code for the finale, I've also found that magwalking was not being properly disabled during the finale, so that has been fixed as well. Hopefully both of these changes will make the finale more consistent and usable.

Steven
